package main.java.util;

public enum AVAILABLE_OPTIONS {
	CLOCK_MODE, TRANSMISSION_MODE, LINE_ENCODING_MODE, FRAME_SYNC_MODE, SHARE_FLAG, INTER_FRAME_TIME_FILL,
	NUMBER_OF_SYNC_BYTES, NUMBER_OF_TERMINATION_BYTES, MASKED_INTERRUPTS_VISIBLE, CRC_FRAME_CHECK_MODE, ORDER_OF_BYTES,
	ADDRES_MODE, RECEIVER_DISABLED, EXTERNAL_SIGNAL_MODE,
}
