/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class main_java_synccom_SYNCCOM_Loader */

#ifndef _Included_main_java_synccom_SYNCCOM_Loader
#define _Included_main_java_synccom_SYNCCOM_Loader
#ifdef __cplusplus
extern "C" {
#endif

#define INITIALIZE_BUFFER(buffer, value) memset(&buffer, value,sizeof(buffer))
/*
 * Class:     main_java_synccom_SYNCCOM_Loader
 * Method:    init
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_main_java_synccom_SYNCCOM_1Loader_init
  (JNIEnv *, jclass);

/*
 * Class:     main_java_synccom_SYNCCOM_Loader
 * Method:    close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_main_java_synccom_SYNCCOM_1Loader_close
  (JNIEnv *, jclass);

/*
 * Class:     main_java_synccom_SYNCCOM_Loader
 * Method:    read
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_main_java_synccom_SYNCCOM_1Loader_read
  (JNIEnv *, jclass);

/*
 * Class:     main_java_synccom_SYNCCOM_Loader
 * Method:    readWithTimeout
 * Signature: (I)[B
 */
JNIEXPORT jbyteArray JNICALL Java_main_java_synccom_SYNCCOM_1Loader_readWithTimeout
  (JNIEnv *, jclass, jint);

/*
 * Class:     main_java_synccom_SYNCCOM_Loader
 * Method:    write
 * Signature: ([B)I
 */
JNIEXPORT jint JNICALL Java_main_java_synccom_SYNCCOM_1Loader_write
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     main_java_synccom_SYNCCOM_Loader
 * Method:    setClockFrequency
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_main_java_synccom_SYNCCOM_1Loader_setClockFrequency
  (JNIEnv *, jclass, jlong);

/*
 * Class:     main_java_synccom_SYNCCOM_Loader
 * Method:    SYNCCOM_GET_REGISTERS
 * Signature: ()Ljava/util/ArrayList;
 */
JNIEXPORT jobject JNICALL Java_main_java_synccom_SYNCCOM_1Loader_SYNCCOM_1GET_1REGISTERS
  (JNIEnv *, jclass);

/*
 * Class:     main_java_synccom_SYNCCOM_Loader
 * Method:    SYNCCOM_SET_REGISTERS
 * Signature: (Ljava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_main_java_synccom_SYNCCOM_1Loader_SYNCCOM_1SET_1REGISTERS
  (JNIEnv *, jclass, jobject);

/*
 * Class:     main_java_synccom_SYNCCOM_Loader
 * Method:    SYNCCOM_PURGE_TX
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_main_java_synccom_SYNCCOM_1Loader_SYNCCOM_1PURGE_1TX
  (JNIEnv *, jclass);

/*
 * Class:     main_java_synccom_SYNCCOM_Loader
 * Method:    SYNCCOM_PURGE_RX
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_main_java_synccom_SYNCCOM_1Loader_SYNCCOM_1PURGE_1RX
  (JNIEnv *, jclass);

/*
 * Class:     main_java_synccom_SYNCCOM_Loader
 * Method:    SYNCCOM_ENABLE_APPEND_STATUS
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_main_java_synccom_SYNCCOM_1Loader_SYNCCOM_1ENABLE_1APPEND_1STATUS
  (JNIEnv *, jclass);

/*
 * Class:     main_java_synccom_SYNCCOM_Loader
 * Method:    SYNCCOM_DISABLE_APPEND_STATUS
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_main_java_synccom_SYNCCOM_1Loader_SYNCCOM_1DISABLE_1APPEND_1STATUS
  (JNIEnv *, jclass);

/*
 * Class:     main_java_synccom_SYNCCOM_Loader
 * Method:    SYNCCOM_GET_APPEND_STATUS
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_main_java_synccom_SYNCCOM_1Loader_SYNCCOM_1GET_1APPEND_1STATUS
  (JNIEnv *, jclass);

/*
 * Class:     main_java_synccom_SYNCCOM_Loader
 * Method:    SYNCCOM_SET_MEMORY_CAP
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_main_java_synccom_SYNCCOM_1Loader_SYNCCOM_1SET_1MEMORY_1CAP
  (JNIEnv *, jclass);

/*
 * Class:     main_java_synccom_SYNCCOM_Loader
 * Method:    SYNCCOM_GET_MEMORY_CAP
 * Signature: (Ljava/util/ArrayList;)Ljava/util/ArrayList;
 */
JNIEXPORT jobject JNICALL Java_main_java_synccom_SYNCCOM_1Loader_SYNCCOM_1GET_1MEMORY_1CAP
  (JNIEnv *, jclass, jobject);

/*
 * Class:     main_java_synccom_SYNCCOM_Loader
 * Method:    SYNCCOM_SET_CLOCK_BITS
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_main_java_synccom_SYNCCOM_1Loader_SYNCCOM_1SET_1CLOCK_1BITS
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     main_java_synccom_SYNCCOM_Loader
 * Method:    SYNCCOM_ENABLE_IGNORE_TIMEOUT
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_main_java_synccom_SYNCCOM_1Loader_SYNCCOM_1ENABLE_1IGNORE_1TIMEOUT
  (JNIEnv *, jclass);

/*
 * Class:     main_java_synccom_SYNCCOM_Loader
 * Method:    SYNCCOM_DISABLE_IGNORE_TIMEOUT
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_main_java_synccom_SYNCCOM_1Loader_SYNCCOM_1DISABLE_1IGNORE_1TIMEOUT
  (JNIEnv *, jclass);

/*
 * Class:     main_java_synccom_SYNCCOM_Loader
 * Method:    SYNCCOM_GET_IGNORE_TIMEOUT
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_main_java_synccom_SYNCCOM_1Loader_SYNCCOM_1GET_1IGNORE_1TIMEOUT
  (JNIEnv *, jclass);

/*
 * Class:     main_java_synccom_SYNCCOM_Loader
 * Method:    SYNCCOM_SET_TX_MODIFIERS
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_main_java_synccom_SYNCCOM_1Loader_SYNCCOM_1SET_1TX_1MODIFIERS
  (JNIEnv *, jclass, jint);

/*
 * Class:     main_java_synccom_SYNCCOM_Loader
 * Method:    SYNCCOM_GET_TX_MODIFIERS
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_main_java_synccom_SYNCCOM_1Loader_SYNCCOM_1GET_1TX_1MODIFIERS
  (JNIEnv *, jclass);

/*
 * Class:     main_java_synccom_SYNCCOM_Loader
 * Method:    SYNCCOM_ENABLE_RX_MULTIPLE
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_main_java_synccom_SYNCCOM_1Loader_SYNCCOM_1ENABLE_1RX_1MULTIPLE
  (JNIEnv *, jclass);

/*
 * Class:     main_java_synccom_SYNCCOM_Loader
 * Method:    SYNCCOM_DISABLE_RX_MULTIPLE
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_main_java_synccom_SYNCCOM_1Loader_SYNCCOM_1DISABLE_1RX_1MULTIPLE
  (JNIEnv *, jclass);

/*
 * Class:     main_java_synccom_SYNCCOM_Loader
 * Method:    SYNCCOM_GET_RX_MULTIPLE
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_main_java_synccom_SYNCCOM_1Loader_SYNCCOM_1GET_1RX_1MULTIPLE
  (JNIEnv *, jclass);

/*
 * Class:     main_java_synccom_SYNCCOM_Loader
 * Method:    SYNCCOM_ENABLE_APPEND_TIMESTAMP
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_main_java_synccom_SYNCCOM_1Loader_SYNCCOM_1ENABLE_1APPEND_1TIMESTAMP
  (JNIEnv *, jclass);

/*
 * Class:     main_java_synccom_SYNCCOM_Loader
 * Method:    SYNCCOM_DISABLE_APPEND_TIMESTAMP
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_main_java_synccom_SYNCCOM_1Loader_SYNCCOM_1DISABLE_1APPEND_1TIMESTAMP
  (JNIEnv *, jclass);

/*
 * Class:     main_java_synccom_SYNCCOM_Loader
 * Method:    SYNCCOM_GET_APPEND_TIMESTAMP
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_main_java_synccom_SYNCCOM_1Loader_SYNCCOM_1GET_1APPEND_1TIMESTAMP
  (JNIEnv *, jclass);

/*
 * Class:     main_java_synccom_SYNCCOM_Loader
 * Method:    SYNCCOM_ENABLE_WAIT_ON_WRITE
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_main_java_synccom_SYNCCOM_1Loader_SYNCCOM_1ENABLE_1WAIT_1ON_1WRITE
  (JNIEnv *, jclass);

/*
 * Class:     main_java_synccom_SYNCCOM_Loader
 * Method:    SYNCCOM_DISABLE_WAIT_ON_WRITE
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_main_java_synccom_SYNCCOM_1Loader_SYNCCOM_1DISABLE_1WAIT_1ON_1WRITE
  (JNIEnv *, jclass);

/*
 * Class:     main_java_synccom_SYNCCOM_Loader
 * Method:    SYNCCOM_GET_WAIT_ON_WRITE
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_main_java_synccom_SYNCCOM_1Loader_SYNCCOM_1GET_1WAIT_1ON_1WRITE
  (JNIEnv *, jclass);

/*
 * Class:     main_java_synccom_SYNCCOM_Loader
 * Method:    SYNCCOM_GET_MEM_USAGE
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_main_java_synccom_SYNCCOM_1Loader_SYNCCOM_1GET_1MEM_1USAGE
  (JNIEnv *, jclass);

/*
 * Class:     main_java_synccom_SYNCCOM_Loader
 * Method:    SYNCCOM_GET_FIRMWARE
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_main_java_synccom_SYNCCOM_1Loader_SYNCCOM_1GET_1FIRMWARE
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
